export default [
    'aandmat kaha',
    'baap ke lavde',
    'chodu',
    'chodoo',
    'choodu',
    'gandu',
    'gaandu',
    'gandoo',
    'bhosad',
    'bhosada',
    'bhosadaa',
    'bhosadaaa',
    'bhosadii',
    'bhosadika',
    'bhosadike',
    'bhosadiki',
    'bosadike',
    'bakrichod',
    'balatkaar',
    'behen ke laude',
    'betichod',
    'bhai chhod',
    'bhayee chod',
    'bhen chhod',
    'bhaynchod',
    'behanchod',
    'behenchod',
    'bhen ke lode',
    'bhosdi',
    'bhosdike',
    'chipkai ki choot ke paseene',
    'cha cha chod',
    'chod ke bal ka kida',
    'chopre he randi',
    'chudasi',
    'chut ka maindak',
    'chutia',
    'chutiya',
    'chootia',
    'chutiye',
    'dheeli choot',
    'choot',
    'chootiya',
    'gaand chaat mera',
    'gaand',
    'gaand ka khadda',
    'gaand ke dhakan',
    'gaand mein kida',
    'gandi chut mein sadta hua ganda kida',
    'gandmasti',
    'jhaat ke baal',
    'jhat lahergaya',
    'jhatoo',
    'jhantu',
    'kukarchod',
    'kutha sala',
    'kuthta buraanahe kandaa nahi pattaahe',
    'lode jesi shakal ke',
    'lode ke baal',
    'lund khajoor',
    'lund chuse',
    'lund',
    'luhnd',
    'lundh',
    'madar chod',
    'maadarchod',
    'maadar',
    'madar',
    'chod',
    'madarchod',
    'madarchod ke aulaad',
    'mader chod',
    'mai chod',
    'mera mume le',
    'mere fudi kha ley',
    'meri ghand ka baal',
    'randi',
    'randi ka choda',
    'suzit',
    'sust lund ki padaish',
    'tatti ander lele',
    'tere baap ki gaand',
    'teri chute mai chuglee',
    'teri gaand mein haathi ka lund',
    'teri maa ki choot',
    'teri maa ki sukhi bhos',
    'teri phuphi ki choot mein',
    'teri bhosri mein aag',
    'teri gaand me danda',
    'teri ma ki choot me bara sa land',
    'teri ma ki chudaye bandar se hui',
    'teri ma randi',
    'teri maa ke bable',
    'teri maa ke bhosade ke baal',
    'tu tera maa ka lauda',
    'amma ki chut',
    'bhaand me jaao',
    'bhadva',
    'bhadve',
    'chodika',
    'bhadwe ki nasal',
    'bhen ke lode maa chuda',
    'bhosad chod',
    'bhosadchod',
    'bhosadi ke',
    'bhosdee kay',
    'bhosdi k',
    'bulle ke baal',
    'bursungha',
    'camina',
    'chod bhangra',
    'choot k bhoot',
    'choot k pakode',
    'choot ka paani',
    'choot ka pissu',
    'choot ki jhilli',
    'chudpagal',
    'chut ke makkhan',
    'chootiye',
    'gaand maar bhen chod',
    'gand mein louda',
    'gandi fuddi ki gandi auladd',
    'haram zaadaa',
    'harami',
    'jhaat',
    'kaala lund',
    'kaali kutti',
    'kuthri',
    'kutte',
    'kutte ki olad',
    'lavde ka baal',
    'lavde',
    'lodu',
    'lowde ka bal',
    'lund k laddu',
    'lund mera muh tera',
    'maa-cho',
    'maal chhodna',
    'mahder chod',
    'mera gota moo may lay',
    'mome ka pasina chat',
    'moo may lay mera',
    'padosi ki aulaad',
    'rand ki moot',
    'randi baj',
    'randi ka larka',
    'randi ke bacche',
    'randi ke beej',
    'saale lm',
    'sab ka lund teri ma ki chut mein',
    'sinak se paida hua',
    'suvar chod',
    'suwar ki aulad',
    'tera gittha',
    'tere maa ka bur',
    'teri behen ka bhosda faadu',
    'teri gand mai ghadhe ka lund',
    'teri ma bahar chud rahi he',
    'teri ma ko kutta chode',
    'teri maa ka bhosra',
    'teri maa ka boba chusu',
    'teri maa ki choot me kutte ka lavda',
    'teri maa ki chut',
    'teri maa ki chute',
    'tuzya aaichi kanda puchi',
    'bhadavya',
    'bhikaar',
    'bulli',
    'chinaal',
    'chut',
    'gand',
    'maadarbhagat',
    'chodubhagat',
    'lundfakir',
    'gandit',
    'jhavadya',
    'laudu',
    'lavadya',
    'muttha',
    'raandichya',
    'madarchoth',
    'गर्भपात',
    'गुदा',
    'नितंब',
    'गधा कमीने',
    'गधे',
    'बेवकूफों',
    'गेंद का थैला',
    'गेंदों',
    'घटिया इंसान',
    'बेल अंत',
    'वहशी',
    'वहशीता',
    'कुतिया',
    'वो साले',
    'bitching',
    'रक्तरंजित',
    'blowjob',
    'bollok',
    'उल्लू',
    'स्तन',
    'स्तनों',
    'buceta',
    'चूतड़',
    'बट',
    'कालीन का चूरा',
    'चिंक',
    'cipa',
    'भगशेफ',
    'मुर्गा',
    'मुर्गा चूसने वाला',
    'मुर्गा के',
    'कून',
    'बकवास',
    'सह',
    'सह शॉट',
    'cunillingus',
    'योनी',
    'अरे नहीं',
    'लिंग',
    'डिल्डो',
    'dink',
    'कुत्ते-कमीने',
    'duche',
    'बांध',
    'बोल पड़ना',
    'ejaculated',
    'ejaculates',
    'ejaculating',
    'फटना',
    'सिगरेट',
    'fagging',
    'होमोसेक्सुअल',
    'fagots',
    'पिछाड़ी',
    'felching',
    'मुखमैथुन',
    'निकला हुआ किनारा',
    'लानत है',
    'गड़बड़',
    'मूर्ख',
    'fuckers',
    'कमबख्त',
    'fuckings',
    'fucks',
    'ठगना पैकर',
    'भगवान-शापित',
    'धत् तेरे की',
    'नरक',
    'होर',
    'सींग का बना हुआ',
    'झटका बंद',
    'कॉक',
    'लेबिया',
    'हवस',
    'lusting',
    'masochist',
    'हस्तमैथुन',
    'माँ कमीने',
    'नाजी',
    'चाकलेट का रंग',
    'जी में आये करो',
    'orgasim',
    'ओगाज़्म',
    'संभोग सुख',
    'चोंच',
    'पेशाब',
    'बहुत मदहोश',
    'pisser',
    'pisses',
    'pissing',
    'दूर जाने का अभद्र संकेत देना',
    'गोली चलाने की आवाज़',
    'पॉर्न',
    'अश्लील',
    'कामोद्दीपक चित्र',
    'चुभन',
    'pube',
    'pussies',
    'बिल्ली',
    'बलात्कार',
    'लुटेरा',
    'मलाशय',
    'काम करना',
    'rimming',
    'पीड़न कामुक',
    'पंगा लेना',
    'अंडकोश की थैली',
    'वीर्य',
    'यौन-संबंध',
    'shagging',
    'किन्नर',
    'मल',
    'shite',
    'शिफ़्ट को',
    'shitted',
    'shitting',
    'shitty',
    'skank',
    'फूहड़',
    'sluts',
    'शिश्नमल',
    'मैल',
    'छीनना',
    'दुष्ट',
    'spac',
    'साहस',
    'अंडा',
    'चूची',
    'titt',
    'turd',
    'योनि',
    'वियाग्रा',
    'वैंग',
    'wank',
    'वेश्या',
    'एक्स रेटेड',
    'bajeko geda',
    'bajiya',
    'beshya',
    'Beshyaka',
    'besiya',
    'beysyaka',
    'Bhalu',
    'bhalu ko poi',
    'Bhalu lai chik muji',
    'bhaluko poi',
    'bhele',
    'boobs',
    'Cement ko bora',
    'Chaak chikaaure',
    'chaak ko pwal',
    'chahk',
    'chahk ko dulka',
    'chak cha kha',
    'chakka muji',
    'CHHIMBAJYA YA PANGRA',
    'Chick-day',
    'Chickne',
    'Chikanthaile',
    'chikimari',
    'Chikne',
    'chimma ma si',
    'choita',
    'Cholrus',
    'Choltaal',
    'Chuste',
    'condo',
    'condo',
    'condo hannay',
    'Damodar',
    'Dankini',
    'Dhoti',
    'dhoti sale',
    'fohori aayimaayi',
    'Fundi',
    'fushi kha',
    'Gadha',
    'gand faat cha',
    'Geda',
    'geda jasto',
    'Gede',
    'Gidi Haps',
    'Goo kha',
    'goo khai',
    'goo khai ra morr',
    'Gula chus randi',
    'gula kha',
    'Gulle',
    'Gwanch',
    'Gwanchi',
    'Gwanchyafool',
    'hijada sala',
    'Jantha',
    'jatha',
    'jatha',
    'jathi',
    'Jhyau',
    'jhykne',
    'kalemoro',
    'kando',
    'Kando',
    'kando kha',
    'Kangres',
    'khate haru',
    'Khatesaley',
    'khiccha',
    'khichani yu kya',
    'khichhani',
    'Khullitta',
    'khwasa macha',
    'kukur',
    'kukur',
    'kukur chikni',
    'kururni',
    'laando kha',
    'Lado',
    'lado',
    'Lado chus',
    'Lado chuschu',
    'lado cocha',
    'Lado kha',
    'lado kha machikne',
    'Lado ko tuppo',
    'lado machikne',
    'Lado Tauke',
    'Lakkad',
    'lamto',
    'LangLang',
    'linga safa garne taalo',
    'ma ka doxx',
    'Ma puti chatxu',
    'ma shaala',
    'maa chikney!',
    'Maa chikni',
    'Maa jhyakne',
    'Maa Rondi!',
    'maachikne',
    'maamfuli',
    'maampakhe',
    'machikne',
    'Machikne',
    'Madhesi',
    'madhesi muji',
    'Makkhi Chus',
    'Makune',
    'mam facka',
    'Mampakha',
    'mandale',
    'maobadi',
    'Masti ko natija',
    'Mathssikne ranjeet ko chhora',
    'mero chus',
    'mero fushi kha',
    'moot',
    'mootday',
    'Morr Sali Morro',
    'morryo',
    'Mugi',
    'muji',
    'muji',
    'Muji',
    'Muji randi ko choro',
    'Mukhya Jimmewar',
    'mula',
    'murda',
    'mya',
    'myachikne',
    'myachis',
    'Paate Muji',
    'pakhe',
    'phusket',
    'pinko',
    'Prachanda',
    'Pufyara',
    'Puti Chat Chus',
    'puti kha',
    'Puti khaa muji',
    'puti ko jhol',
    'Putin Chaat',
    'r4nd1',
    'Raame ko chhora',
    'Rada baan',
    'rada ban',
    'radi ko puti',
    'Randi ko baan',
    'Randi ko Ban',
    'randi ko ban sala haru.',
    'randi ko choro',
    'randiko chhora',
    'randiko choro',
    'RanMaaili',
    'sala',
    'sungghur',
    'Teri aama chikne',
    'Teri aama ko kalo Chak',
    'Teri ija liu',
    'terimachikne',
    'tero baje',
    'TERO BAJE KO PANGRA',
    'tero baje ko turi',
    'tero bajeko naito',
    'tero bau',
    'Tero bau muji',
    'tero kando ma churn parna nasakeko',
    'tero tauko',
    'tessima',
    'tessima jhakne',
    'Tori',
    'tori raixa yo ta',
    'turi tauke',
    'Tutturay',
    'Tyape',
    'yesi maa jhyakne',
    'अदगल्या',
    'अद्गल्या',
    'आमाचकारी',
    'कट्कनु',
    'कठचोद्नी',
    'कठ्युन',
    'कन्चनी',
    'कन्डो-',
    'कन्धने',
    'कमिना',
    'काउडो',
    'काटि खानो',
    'कातरो',
    'कालीकुच्ची',
    'कुच्छेद',
    'कुत्ती',
    'कुवाच्य',
    'कोच्च्याउनो',
    'कोर्‍या',
    'कोर्‍याहा',
    'कौद पड्नु',
    'खपक',
    'खान नपाएको लोभी',
    'खाल्डामा पुर्नु',
    'खुट्टा नचल्ने भइस्',
    'खुट्ट्यासो',
    'खै',
    'खोप्डी',
    'गगने',
    'गधा',
    'गर्दने',
    'गाँडीमुखे',
    'गासेगास्से',
    'गास्से',
    'गिद्देनी',
    'गुखात',
    'गुला',
    'गुवालगाली',
    'गोक्ते',
    'गोल्लाँडे',
    'घंटा',
    'घण्टा',
    'घण्टा गर्नु',
    'घन्टा',
    'घन्टा',
    'चकार',
    'चट्टोपाध्याय',
    'चाक',
    'चाक हान्नु',
    'चास्नी',
    'चिक्नु',
    'चिक्नु',
    'चिक्ने',
    'चिक्ने',
    'चितुवा',
    'चिलको आहारा',
    'चुका',
    'चुडेल',
    'चुत्याहा',
    'चेड्यानी',
    'चौँठे',
    'छारछर्बट्टै',
    'छिनारी',
    'छुछनहर',
    'छेपन',
    'छेराउटी',
    'छोरी कुटाइ',
    'छोसछास',
    'जगटो',
    'जाँठा',
    'जाँठा',
    'जाँठी',
    'जाँठो',
    'जाँठो',
    'झाँट',
    'झोल खानु',
    'टँगालो',
    'टडी',
    'टपरेकाठो',
    'टाकेटुरो',
    'टुन्टे',
    'टुहुरो मोरो',
    'टोकस्नु',
    'ठँडौरो',
    'ठन्कनु',
    'ठन्काउनु',
    'ठन्टी',
    'ठाँगे',
    'ठाँडो',
    'ठोक्नु',
    'डक्नु',
    'डङ्किनी',
    'डबर्‍युनु',
    'डाकुली काटिनु',
    'डाँक्ले',
    'डाट्ठु',
    'डाँट्नु',
    'डाडो',
    'डिँगनु',
    'डिँगनो',
    'ढुङामाइ रनु',
    'ढोल्लो',
    'तातै जानु',
    'तिलङ्गे माइकी',
    'तेर ज्याकी मुन्डी',
    'तेरिमा',
    'थात्रो',
    'थु थु',
    'थुक्क',
    'थुँग्नु',
    'थेचरो',
    'थेच्चर',
    'थेत्तरो',
    'दपक्याउनु',
    'दपेट',
    'धारिउँहात',
    'धिक्',
    'धिङ्न्याहा',
    'धोइलो गद्दु',
    'नाङो नाच',
    'नाङ्गो',
    'नाथे',
    'पट्के',
    'पडो',
    'पणि',
    'पति हाल्लु',
    'परिभाषण',
    'पाजी',
    'पाँडेगाली',
    'पाँडेगाली',
    'पिशाचिनी',
    'पुती',
    'पूती',
    'पूती',
    'फजित',
    'फड्कार',
    'फलाको',
    'फुसी',
    'बच्चेट',
    'बजिनी',
    'बजिया',
    'बपचोदी',
    'बर्चेट',
    'बर्चोट',
    'बर्चोट',
    'बाघे',
    'बान्चेट',
    'बान्चोट',
    'बान्चोद',
    'बाहान्चोट',
    'बिलापी',
    'बिहाली',
    'बुद्रुङ',
    'बुरचोदी',
    'बेस्से',
    'बोक्सीको छौंडा',
    'बोक्सेबुढो',
    'भालू',
    'भुकुल्ला',
    'भुत्रो',
    'भुत्रो',
    'भुसडी',
    'मरेस्',
    'मरोस्',
    'मा चिक्ने',
    'माचिक्नी',
    'माचोत',
    'मुजी',
    'मुजी',
    'मुत्नु',
    'मुत्ने',
    'मुर्कट्या',
    'मुलङ्खरे',
    'मुलन्धरे',
    'मूला साग',
    'मोरामोरी',
    'मोरी',
    'मोरो',
    'योनि चिक्नु',
    'योनी',
    'रगतानी',
    'रडाउनु',
    'रंडी',
    'रण्डी',
    'रण्डी',
    'रन्डी',
    'राँड',
    'राँडभाँड',
    'राँडाराँडी',
    'राँडाराँडी',
    'राँडी',
    'राँडीको छोरो',
    'राँडीको पोइ',
    'रिँग्ने',
    'रुँगालो',
    'लडे',
    'लाडो',
    'लाँडो',
    'लाँडो',
    'लाँडो',
    'लाँडो खा',
    'लादो',
    'लिँडे',
    'लोटुनो',
    'वाहान्चोट',
    'वेश्या',
    'साइँदुवा',
    'साइँधुवा',
    'साँड',
    'साँप्रो',
    'साला',
    'साले',
    'सिल्कुन',
    'हगुवा',
    'हग्नु',
    'हग्ने',
    'हल्लुँडो',
    'हाँडीखाउडे',
    'Bandar Ko Chaak',
    'Bhalu',
    'Chick-day',
    'Chickne',
    'Dhoti',
    'Goo kha',
    'Gula chus randi',
    'Jantha',
    'Kangres',
    'Lado',
    'Lado chus',
    'Lado kha',
    'Lado ko tuppo',
    'Lang Lang',
    'Maa Rondi!',
    'Maa chikni',
    'Machikne',
    'Madhesi',
    'Morr Sali Morr!',
    'Muji',
    'Prachanda',
    'Puti Chat Chu',
    'Putin Chaat',
    'Putin Chaat',
    'Tutturay',
    'beshya',
    'bhalu ko poi',
    'chaak ko pwal',
    'chahk',
    'chahk ko dulka',
    'chak cha',
    'condo',
    'condo hannay',
    'dudh',
    'fushi kha',
    'gand faat cha',
    'goo kha',
    'goo khai-ra morr',
    'gula kha',
    'kukur chikni',
    'laando kha',
    'lado',
    'lado cocha',
    'lamto',
    'ma shaala',
    'maa chikney!',
    'mandale',
    'maobadi',
    'mero fushi kha',
    'moot',
    'mootday',
    'moreko',
    'moreko manchi',
    'morryo',
    'murda',
    'muzy',
    'pahadi',
    'randi ko choro',
    'pinko',
    'puti kha',
    'randiko choro',
    'sungghur',
    'turi tauke'
];
